
create table tb_conteudo (id int8 generated by default as identity, texto varchar(255), titulo varchar(255),assunto, image_uri varchar(255), nivel int4, primary key (id));
create table tb_conteudo_disciplina (conteudo_id int8 not null, disciplina_id int8 not null, primary key (conteudo_id, disciplina_id));
create table tb_disciplina (id int8 generated by default as identity, name varchar(255) primary key (id));
alter table if exists tb_conteudo_disciplina add constraint FKsu03ywlcvyqg5y78qey2q25lc foreign key (disciplina_id) references tb_disciplina;
alter table if exists tb_conteudo_disciplina add constraint FK40anaevs16kmc2tbh7wc511fq foreign key (conteudo_id) references tb_conteudo;
